### ISSUE TITLE
How much "randomness" is required?

### ISSUE THREAD

**Issue by lalaithion** [niofis/raybench#13]
The Haskell implementation can get a ~20x speedup if the random rays are the same rays in each pixel, and the normal rays for each bounce are the same. This feels somewhat like a cheat, though. 

I think there's an opportunity for a speedup still in Haskell even if this is unacceptable, but I want to know where people stand before I submit a pull request.

**Comment by niofis** [comment]
Not much really, as long as the final image looks fine then it would be ok. This is only a toy renderer, for more serious ones, that requirement might be much more strict. If you want to send a PR it would be more than welcome.

**Comment by jdz** [comment]
Is writing poor substitutes for standard library functions considered "ideomatic C"?

https://github.com/niofis/raybench/blob/master/crb.c#L221-L236

**Comment by niofis** [comment]
That's a good question that I'm still trying to cope with; I added this implementation to address the main issue with this benchmark: **not all RNGs are equal**. The current numbers in the README have not been updated, but using the Xorshift algorithm makes C and Rust (with XorShiftRng) almost equal in performance, thus, hinting this is a fairer comparison.

**Comment by jdz** [comment]
As @lalaithion says, the choice of random number generator greatly impacts the benchmark results.  And I suspect that apples are being compared to oranges, since for most programming languages in this benchmark random number generators from the language's standard library are being used.  It seems impractical to expect all language implementations to use the same RNG implementation, and since this choice has dramatic impact on benchmark results I'd say the benchmark is flawed.

The best thing to do would be to remove the randomness from the benchmark.  Considering this the proposed solution of using the same "random" number is not cheating at all.  I'd even claim that not doing this is cheating.
