### ISSUE TITLE
Is this a valid benchmark?

### ISSUE THREAD

**Issue by ns-cweber** [niofis/raybench#15]
I was thinking about it this morning, and I think this benchmark might be largely invalid insofar as the different pseudorandom number generators output different values which likely affect the number of loop iterations. Further, I'm not sure anything is controlling for correctness of output.

It seems like it would be better to generate the same vectors for every program (e.g., write a program in any language to generate a vector file, commit both the program and the output to git, and have every program begin by loading the file). This should mean all benchmark programs have the same output, allowing you to validate them.

EDIT: I should disclaim that I know nothing about raytracing other than what I garnered from reading the source code. Maybe there needs to be some element of "randomness" in the domain, but a good benchmark depends on controlling that randomness such that the RNG produces the same sequences for each program (determinism).

**Comment by niofis** [comment]
To be honest, I didn't mind much about validness when starting this project, but as time passed and found wide varying differences in performance I started to think more and more about it, which prompted me to do some more testing, taking me to the following conclusion: the main problem with the benchmark is the RNG, but not for the reasons you might be thinking.

To address your first concern; the number of loops is not affected by the randomness, but how deep the recursion goes is, although it's capped to 5 levels deep. On the other hand, the implemented algorithm is a monte carlo simulation of light bouncing around, and as such, that means that the resulting runtime and exported image should be pretty similar between runs with different RNG seeds, although that greatly depends on how good the RNG algorithm is.

Now, how does the RNG affects the results?, well, for one the C std lib random generator is slower than the one in Nim and Rust, it's also thread safe so adding OpenMP directives make no change in runtime, at all. That is because they use much different algorithms internally, with different strengths and weaknesses.

On the other hand, your suggestion of generating a vector of random numbers to be used is a good one. This would mean taking out of the equation the quality and speed of each language's RNG, making it a deterministic benchmark. In this regard, I started implementing a pseudorandom number generator called Xorshift in some languages to even the playing field.

But then the question remains, should the benchmark take into account the supplied standard libraries? I'm inclining to no, at least for the RNG. Going this way would greatly simplify the Haskell implementation, and make it much easier to use multiple threads in others. But some more caution must be taken as some languages, like Nim, might want to generate the final image in compile time if it deducts that there is no change in output from run to run of the program.

**Comment by ns-cweber** [comment]
> To address your first concern; the number of loops is not affected by the randomness, but how deep the recursion goes is, although it's capped to 5 levels deep

This is true for the outermost loops, but within the rnd_dome() function, the loop condition is derived from `randf` calls. Perhaps this is negligible, however.

> But then the question remains, should the benchmark take into account the supplied standard libraries? I'm inclining to no, at least for the RNG.

I don't think the benchmark is particularly meaningful if it includes the RNG. IMO, If someone wanted to compare RNG implementations, it would make more sense to create a dedicated benchmark.

**Comment by niofis** [comment]
> This is true for the outermost loops, but within the rnd_dome() function, the loop condition is derived from `randf` calls. Perhaps this is negligible, however.

That is correct, but it's not very meaningful for the runtime in general as the work done here is minimal compared to other parts of the benchmark. It also is the standard way of randomly generating a vector for the upper half hemisphere of the unit circle, required for path tracing.


> I don't think the benchmark is particularly meaningful if it includes the RNG. IMO, If someone wanted to compare RNG implementations, it would make more sense to create a dedicated benchmark.

I agree with this, that's why the newest C implementation uses Xorshift pseudorandom generator. I'm also planning on doing the same for other languages.
